name: Build and test artifact - create draft if main branch

on:
  push:
    branches:
      - '**'

jobs:
  build-main-and-feature-branch:
    uses: navikt/dok-workflows/.github/workflows/build-artifact.yml@main
    with:
      java-version: '17'
    secrets: inherit
