name: Manual deployment of ref to environment
run-name: Manual deploy of {{env.DEPLOY_REF}} to ${{inputs.environment}} by @${{github.actor}}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'q2'
        type: choice
        options:
          - p
          - q1
          - q2
      ref_name:
        description: 'Git ref_name. branch or tag'
        required: true
        type: string
        default: 'Replace with tag or branch'

env:
  DEPLOY_REF: ${{(contains(fromJson('["tag", "branch"]'), github.ref_type) && !contains(fromJson('["main", "master"]'), github.ref_name)) && github.ref_name || inputs.ref_name}
  DEPLOY_CLUSTER: ${{github.event.inputs.environment == 'p' && 'prod-fss' || 'dev-fss' }}

jobs:
  deploy-env:
    uses: navikt/dok-workflows/.github/workflows/deploy-nais-app-with-custom-checkout.yml@702b8b0a6accd55ab4f513cf74f016a163a62fa8
    secrets: inherit
    with:
      build-tag: ${{env.DEPLOY_REF}}
      nav-cluster: ${{env.DEPLOY_CLUSTER}}
      nav-environment: ${{inputs.environment}}